language: python
python:
  - "2.7"
  - "3.6"
branches:
  # Restrict push builds to only master
  only:
  - master
before_install:
  - set -e
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  - make tests
